laptop.register_theme("Amber Shell", {
	desktop_background = "laptop_theme_ambershell_desktop_background.png",
	app_background = "laptop_theme_ambershell_app_background.png",
	major_button = "laptop_theme_ambershell_major_button.png",
	major_textcolor = "#FFB000",
	minor_button = "laptop_theme_ambershell_minor_button.png",
	minor_textcolor = "#000000",
	back_button = "laptop_theme_ambershell_back_button.png",	
	back_textcolor = "#000000",
	exit_button = "laptop_theme_ambershell_exit_button.png",
	exit_character = " ",
	desktop_icon_button = "laptop_theme_desktop_icon_label_button_black.png",
	taskbar_clock_position_and_size = "9,3.5;4,2",
	desktop_icon_label_button = "laptop_theme_desktop_icon_label_button_black.png",
	desktop_icon_label_textcolor = '#FFB000',
	titlebar_textcolor = "#000000",
	textcolor = "#FFB000",
	os_max_version = '3.11',
})
