laptop.register_theme("Boing!", {
	launcher_bg = "laptop_theme_boing_launcher_bg.png",
	app_bg = "laptop_theme_boing_app_bg.png",
	major_button = "laptop_theme_boing_major_button.png",
	major_textcolor = "#ffffff",
	minor_button = "laptop_theme_snowpines_minor_button.png",
	minor_textcolor = "AAAAAA",
	back_button = "laptop_theme_boing_back_button.png",	
	back_textcolor = "#000000",
	exit_button = "laptop_theme_boing_exit_button.png",
	exit_character = " ",
	app_button = "blank.png",
	textcolor = "#000000",
	desktop_icon_label_textcolor = "#ffffff",
	taskbar_clock_position_and_size = "11,-.25;4,0.4",
	desktop_icon_label_button = "laptop_theme_boing_major_button.png",
	titlebar_textcolor = "#000000",
})
