laptop.register_theme("Green Shell", {
	desktop_background = "laptop_theme_greenshell_desktop_background.png",
	app_background = "laptop_theme_greenshell_app_background.png",
	major_button = "laptop_theme_greenshell_major_button.png",
	major_textcolor = "#00FF33",
	minor_button = "laptop_theme_greenshell_minor_button.png",
	back_button = "laptop_theme_greenshell_back_button.png",
	back_textcolor = "#000000",
	exit_button = "laptop_theme_greenshell_exit_button.png",
	exit_character = " ",
	contrast_background = "laptop_theme_greenshell_major_button.png",
	contrast_textcolor = "#00FF33",
	desktop_icon_button = "laptop_theme_desktop_icon_label_button_black.png",
	taskbar_clock_position_and_size = "9,3.5;4,2",
	desktop_icon_label_textcolor = '#00FF33',
	titlebar_textcolor = "#000000",
	textcolor = "#00FF33",
	os_max_version = '3.99',
})
