laptop.register_theme("Snow Pines", {
	desktop_background = "laptop_theme_snowpines_desktop_background.png",
	app_background = "laptop_theme_snowpines_app_background.png",
	major_button = "laptop_theme_snowpines_major_button.png",
	major_textcolor = "#ffffff",
	minor_button = "laptop_theme_snowpines_minor_button.png",
	minor_textcolor = "#ffffff",
	back_button = "laptop_theme_snowpines_exit_button.png",	
	back_textcolor = "#000000",
	exit_button = "laptop_theme_snowpines_exit_button.png",
	exit_textcolor = "#000000",
	contrast_background = "laptop_theme_snowpines_major_button.png",
	desktop_icon_button = "blank.png",
	taskbar_clock_position_and_size = "5.5,-.31;4,0.7",
	os_min_version = '7.00',
})
